import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Colaborador, Departamento } from '../../core/models/itam.models';
import { ColaboradoresService } from '../../core/services/colaboradores.service';
import { ConfirmationService } from '../../core/services/confirmation.service';
import { DepartamentosService } from '../../core/services/departamentos.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-colaboradores-list',imports:[FormsModule,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Colaboradores" subtitle="Personas habilitadas para recibir activos y líneas corporativas."><a class="btn btn--primary" routerLink="nuevo">+ Nuevo colaborador</a></app-page-header>
@if(notice()){<div class="notice notice--success">{{notice()}}</div>}@if(actionError()){<div class="notice notice--error">{{actionError()}}</div>}
<section class="card"><form class="toolbar" (ngSubmit)="load()"><div class="field"><label for="name">Nombre</label><input id="name" name="name" [(ngModel)]="filters.nombre" placeholder="Buscar por nombre" /></div><div class="field"><label for="rut">RUT</label><input id="rut" name="rut" [(ngModel)]="filters.rut" placeholder="12.345.678-9" /></div><div class="field"><label for="department">Departamento</label><select id="department" name="department" [(ngModel)]="filters.departamentoId"><option value="">Todos</option>@for(item of departments();track item.id){<option [value]="item.id">{{item.nombre}}</option>}</select></div><div class="field"><label for="active">Estado</label><select id="active" name="active" [(ngModel)]="active"><option value="">Todos</option><option value="true">Activos</option><option value="false">Inactivos</option></select></div><div class="toolbar-actions"><button class="btn btn--primary" type="submit">Filtrar</button><button class="btn btn--secondary" type="button" (click)="clear()">Limpiar</button></div></form>
@if(loading()){<app-view-state kind="loading" title="Cargando colaboradores" />}@else if(error()){<app-view-state kind="error" title="No se pudo cargar" [message]="error()" (retry)="load()" />}@else if(!items().length){<app-view-state kind="empty" title="Sin resultados" message="No hay colaboradores que coincidan con los filtros." />}@else{<div class="table-wrap"><table class="data-table"><thead><tr><th>Colaborador</th><th>RUT</th><th>Cargo</th><th>Departamento</th><th>Estado</th><th></th></tr></thead><tbody>@for(item of items();track item.id){<tr><td><a class="cell-primary link" [routerLink]="[item.id]">{{item.nombre}}</a><span class="cell-secondary">{{item.localidad||'Sin localidad'}}</span></td><td>{{item.rut}}</td><td>{{item.cargo||'—'}}</td><td>{{item.departamento?.nombre||'Sin departamento'}}</td><td><app-status-badge [code]="item.activo" [label]="item.activo?'Activo':'Inactivo'" /></td><td><div class="actions"><a class="btn btn--ghost btn--small" [routerLink]="[item.id]">Ver</a><a class="btn btn--ghost btn--small" [routerLink]="[item.id,'editar']">Editar</a>@if(item.activo){<button class="btn btn--danger btn--small" type="button" (click)="deactivate(item)">Desactivar</button>}</div></td></tr>}</tbody></table></div>}</section>`,styles:[`.link{color:var(--color-primary);text-decoration:none}`]})
export class ColaboradoresList implements OnInit{
 private readonly service=inject(ColaboradoresService);private readonly deptService=inject(DepartamentosService);private readonly confirmation=inject(ConfirmationService);
 protected readonly items=signal<Colaborador[]>([]);protected readonly departments=signal<Departamento[]>([]);protected readonly loading=signal(true);protected readonly error=signal('');protected readonly notice=signal('');protected readonly actionError=signal('');protected filters:{nombre:string;rut:string;departamentoId:string}={nombre:'',rut:'',departamentoId:''};protected active='';
 ngOnInit(){this.deptService.listar().subscribe({next:i=>this.departments.set(i.filter(d=>d.activo))});this.load()}
 protected load(){this.loading.set(true);this.error.set('');this.service.listar({nombre:this.filters.nombre||undefined,rut:this.filters.rut||undefined,departamentoId:this.filters.departamentoId?Number(this.filters.departamentoId):undefined,activo:this.active===''?undefined:this.active==='true'}).subscribe({next:i=>{this.items.set(i);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}
 protected clear(){this.filters={nombre:'',rut:'',departamentoId:''};this.active='';this.load()}
 protected deactivate(item:Colaborador){if(!this.confirmation.confirm(`¿Desactivar a ${item.nombre}?`))return;this.service.actualizar(item.id,{activo:false}).subscribe({next:updated=>{this.items.update(items=>items.map(i=>i.id===updated.id?updated:i));this.notice.set('Colaborador desactivado correctamente.')},error:e=>this.actionError.set(errorMessage(e))})}
}
