import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Colaborador } from '../../core/models/itam.models';
import { ColaboradoresService } from '../../core/services/colaboradores.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-colaborador-detail',imports:[DatePipe,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Detalle del colaborador" subtitle="Identificación y adscripción vigentes.">@if(item()){<a class="btn btn--secondary" [routerLink]="['editar']">Editar</a>}</app-page-header>
@if(loading()){<section class="card"><app-view-state kind="loading" title="Cargando detalle" /></section>}@else if(error()){<section class="card"><app-view-state kind="error" title="No se pudo cargar" [message]="error()" /></section>}@else if(item();as c){<section class="card detail-card"><div class="detail-title"><div><span class="initial">{{c.nombre.charAt(0)}}</span><div><h2>{{c.nombre}}</h2><p>{{c.rut}}</p></div></div><app-status-badge [code]="c.activo" [label]="c.activo?'Activo':'Inactivo'" /></div><dl class="detail-grid"><div class="detail-item"><dt>Cargo</dt><dd>{{c.cargo||'—'}}</dd></div><div class="detail-item"><dt>Departamento</dt><dd>{{c.departamento?.nombre||'Sin departamento'}}</dd></div><div class="detail-item"><dt>Localidad</dt><dd>{{c.localidad||'—'}}</dd></div><div class="detail-item"><dt>Creado</dt><dd>{{c.creadoEn|date:'dd-MM-yyyy HH:mm'}}</dd></div><div class="detail-item"><dt>Última actualización</dt><dd>{{c.actualizadoEn|date:'dd-MM-yyyy HH:mm'}}</dd></div><div class="detail-item"><dt>Observaciones</dt><dd>{{c.observaciones||'—'}}</dd></div></dl></section>}`,styles:[`.detail-card{padding:1.4rem}.detail-title{align-items:center;border-bottom:1px solid var(--color-border);display:flex;justify-content:space-between;margin-bottom:1.2rem;padding-bottom:1.2rem}.detail-title>div{align-items:center;display:flex;gap:.8rem}.detail-title h2{font-size:1.2rem;margin:0}.detail-title p{color:var(--color-muted);margin:.2rem 0 0}.initial{align-items:center;background:var(--color-primary-soft);border-radius:.7rem;color:var(--color-primary);display:flex;font-size:1.15rem;font-weight:850;height:2.8rem;justify-content:center;width:2.8rem}`]})
export class ColaboradorDetail implements OnInit{private readonly service=inject(ColaboradoresService);private readonly route=inject(ActivatedRoute);protected readonly item=signal<Colaborador|null>(null);protected readonly loading=signal(true);protected readonly error=signal('');ngOnInit(){const id=this.route.snapshot.paramMap.get('id')||'';this.service.obtener(id).subscribe({next:i=>{this.item.set(i);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}}
