import type {Request,Response} from "express";
import {asyncHandler} from "../../shared/async-handler";
import {authenticatedActorName} from "../../shared/authenticated-actor";
import {sendCollection,sendItem} from "../../shared/responses";
import {parseBodyObject,parseEnum,parseOptionalNonNegativeInteger,parseOptionalString,parsePositiveInteger,parseRequiredString} from "../../shared/validation";
import {ValidationError} from "../../shared/errors";
import {cerrarEquipoTemporal,cerrarOrdenServicio,crearOrdenServicio,decidirOrdenServicio,entregarEquipoTemporal,generarEnvioServicioPdf,obtenerOrdenServicio,obtenerOrdenesServicio,registrarCotizacion} from "./servicio-tecnico.service";

const money=(value:unknown,field:string)=>{const parsed=parseOptionalNonNegativeInteger(value,field);if(parsed===undefined||parsed===null)throw new ValidationError(`${field} es obligatorio.`);return parsed};
export const listarOrdenesController=asyncHandler(async(_req:Request,res:Response)=>sendCollection(res,await obtenerOrdenesServicio()));
export const obtenerOrdenController=asyncHandler(async(req:Request,res:Response)=>sendItem(res,await obtenerOrdenServicio(parsePositiveInteger(req.params.id,"id"))));
export const crearOrdenController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await crearOrdenServicio({dispositivoCodigo:parsePositiveInteger(b.dispositivoCodigo,"dispositivoCodigo"),proveedor:parseOptionalString(b.proveedor,"proveedor",180),fechaEnvio:parseOptionalString(b.fechaEnvio,"fechaEnvio",40),fallaReportada:parseRequiredString(b.fallaReportada,"fallaReportada"),observaciones:parseOptionalString(b.observaciones,"observaciones"),responsable:authenticatedActorName(req)}),201)});
export const envioPdfController=asyncHandler(async(req:Request,res:Response)=>{const pdf=await generarEnvioServicioPdf(parsePositiveInteger(req.params.id,"id"));res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",'attachment; filename="'+pdf.filename+'"');res.send(pdf.buffer)});
export const cotizarOrdenController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await registrarCotizacion(parsePositiveInteger(req.params.id,"id"),{diagnostico:parseRequiredString(b.diagnostico,"diagnostico"),descripcionReparacion:parseRequiredString(b.descripcionReparacion,"descripcionReparacion"),montoCotizacion:money(b.montoCotizacion,"montoCotizacion"),proveedor:parseOptionalString(b.proveedor,"proveedor",180),responsable:authenticatedActorName(req)}))});
export const decidirOrdenController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await decidirOrdenServicio(parsePositiveInteger(req.params.id,"id"),{decision:parseEnum(b.decision,"decision",["APROBAR","RECHAZAR","DAR_BAJA"] as const),motivo:parseOptionalString(b.motivo,"motivo",80),observaciones:parseOptionalString(b.observaciones,"observaciones"),responsable:authenticatedActorName(req)}))});
export const cerrarOrdenController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await cerrarOrdenServicio(parsePositiveInteger(req.params.id,"id"),{costoFinal:money(b.costoFinal,"costoFinal"),fechaRetorno:parseOptionalString(b.fechaRetorno,"fechaRetorno",40),resultado:parseRequiredString(b.resultado,"resultado"),responsable:authenticatedActorName(req)}))});
export const entregarTemporalController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await entregarEquipoTemporal(parsePositiveInteger(req.params.id,"id"),{dispositivoCodigo:parsePositiveInteger(b.dispositivoCodigo,"dispositivoCodigo"),responsable:authenticatedActorName(req),observaciones:parseOptionalString(b.observaciones,"observaciones")}))});
export const cerrarTemporalController=asyncHandler(async(req:Request,res:Response)=>{const b=parseBodyObject(req.body);sendItem(res,await cerrarEquipoTemporal(parsePositiveInteger(req.params.id,"id"),parsePositiveInteger(req.params.entregaId,"entregaId"),{responsable:authenticatedActorName(req),observaciones:parseOptionalString(b.observaciones,"observaciones")}))});
