import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Departamento, Dispositivo, Estado } from '../../core/models/itam.models';
import { DepartamentosService } from '../../core/services/departamentos.service';
import { DispositivosService } from '../../core/services/dispositivos.service';
import { EstadosService } from '../../core/services/estados.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-dispositivos-list',imports:[FormsModule,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Dispositivos" subtitle="Inventario físico, custodias y condición operativa."><a class="btn btn--primary" routerLink="nuevo">+ Nuevo dispositivo</a></app-page-header>
<section class="card"><form class="toolbar" (ngSubmit)="load()"><div class="field"><label for="q">Búsqueda</label><input id="q" name="q" [(ngModel)]="filters.q" placeholder="Código, serie, marca o modelo" /></div><div class="field"><label for="tipo">Tipo</label><input id="tipo" name="tipo" [(ngModel)]="filters.tipo" placeholder="Notebook, teléfono…" /></div><div class="field"><label for="estado">Estado</label><select id="estado" name="estado" [(ngModel)]="filters.estado"><option value="">Todos</option>@for(e of states();track e.id){<option [value]="e.codigo">{{e.nombre}}</option>}</select></div><div class="field"><label for="department">Departamento</label><select id="department" name="department" [(ngModel)]="filters.departamentoId"><option value="">Todos</option>@for(d of departments();track d.id){<option [value]="d.id">{{d.nombre}}</option>}</select></div><div class="field"><label for="location">Localidad</label><input id="location" name="location" [(ngModel)]="filters.localidad" /></div><div class="toolbar-actions"><button class="btn btn--primary" type="submit">Filtrar</button><button class="btn btn--secondary" type="button" (click)="clear()">Limpiar</button></div></form>
@if(loading()){<app-view-state kind="loading" title="Cargando dispositivos" />}@else if(error()){<app-view-state kind="error" title="No se pudo cargar" [message]="error()" (retry)="load()" />}@else if(!items().length){<app-view-state kind="empty" title="Sin resultados" message="No hay dispositivos que coincidan con los filtros." />}@else{<div class="table-wrap"><table class="data-table"><thead><tr><th>Activo</th><th>Equipo</th><th>Estado</th><th>Custodia</th><th>Localidad</th><th></th></tr></thead><tbody>@for(item of items();track item.id){<tr><td><a class="asset-link" [routerLink]="[item.codigoInventario]">#{{item.codigoInventario}}</a><span class="cell-secondary">{{item.numeroSerie||'Sin serie'}}</span></td><td><span class="cell-primary">{{item.tipoDispositivo}}</span><span class="cell-secondary">{{item.marca||'—'}} {{item.modelo||''}}</span></td><td><app-status-badge [code]="item.estado.codigo" [label]="item.estado.nombre" /></td><td>{{custody(item)}}<span class="cell-secondary">{{item.departamento?.nombre||item.colaborador?.cargo||''}}</span></td><td>{{item.localidad||'—'}}</td><td><div class="actions"><a class="btn btn--ghost btn--small" [routerLink]="[item.codigoInventario]">Ver</a><a class="btn btn--ghost btn--small" [routerLink]="[item.codigoInventario,'editar']">Editar</a></div></td></tr>}</tbody></table></div>}</section>`,styles:[`.asset-link{color:var(--color-primary);font-weight:800;text-decoration:none}`]})
export class DispositivosList implements OnInit{
 private readonly service=inject(DispositivosService);private readonly estados=inject(EstadosService);private readonly deptService=inject(DepartamentosService);
 protected readonly items=signal<Dispositivo[]>([]);protected readonly states=signal<Estado[]>([]);protected readonly departments=signal<Departamento[]>([]);protected readonly loading=signal(true);protected readonly error=signal('');protected filters={q:'',tipo:'',estado:'',departamentoId:'',localidad:''};
 ngOnInit(){this.estados.listar('DISPOSITIVO').subscribe({next:i=>this.states.set(i)});this.deptService.listar().subscribe({next:i=>this.departments.set(i)});this.load()}
 protected load(){this.loading.set(true);this.error.set('');this.service.listar({q:this.filters.q||undefined,tipo:this.filters.tipo||undefined,estado:this.filters.estado||undefined,departamentoId:this.filters.departamentoId?Number(this.filters.departamentoId):undefined,localidad:this.filters.localidad||undefined}).subscribe({next:i=>{this.items.set(i);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}
 protected clear(){this.filters={q:'',tipo:'',estado:'',departamentoId:'',localidad:''};this.load()}protected custody(i:Dispositivo){return i.colaborador?.nombre||i.departamento?.nombre||'Sin custodia'}
}
