import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { DispositivosService } from '../../core/services/dispositivos.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-dispositivo-form',imports:[ReactiveFormsModule,RouterLink,PageHeader,ViewState],template:`
<app-page-header [title]="codigo?'Editar dispositivo':'Nuevo dispositivo'" subtitle="Registro técnico del activo. Estado y custodia se gestionan desde su detalle." />
@if(loading()){<section class="card"><app-view-state kind="loading" title="Cargando dispositivo" /></section>}@else{<form class="card form-card" [formGroup]="form" (ngSubmit)="submit()">@if(apiError()){<div class="notice notice--error">{{apiError()}}</div>}
<div class="form-grid">@if(!codigo){<div class="field"><label for="codigo">Código de inventario *</label><input id="codigo" type="number" min="1" formControlName="codigoInventario" [class.invalid]="invalid('codigoInventario')" />@if(invalid('codigoInventario')){<p class="field-error">Debe ser un entero positivo.</p>}</div>}@else{<div class="field"><label>Código de inventario</label><input [value]="codigo" disabled /></div>}<div class="field"><label for="tipo">Tipo de dispositivo *</label><input id="tipo" maxlength="80" formControlName="tipoDispositivo" [class.invalid]="invalid('tipoDispositivo')" />@if(invalid('tipoDispositivo')){<p class="field-error">El tipo es obligatorio (máximo 80 caracteres).</p>}</div><div class="field"><label for="marca">Marca</label><input id="marca" maxlength="100" formControlName="marca" /></div><div class="field"><label for="modelo">Modelo</label><input id="modelo" maxlength="150" formControlName="modelo" /></div><div class="field"><label for="serie">Número de serie</label><input id="serie" maxlength="150" formControlName="numeroSerie" /></div><div class="field"><label for="imei">IMEI</label><input id="imei" maxlength="30" formControlName="imei" /></div><div class="field"><label for="localidad">Localidad</label><input id="localidad" maxlength="120" formControlName="localidad" /></div><div class="field"><label for="ubicacion">Ubicación detallada</label><input id="ubicacion" maxlength="250" formControlName="ubicacionDetalle" /></div><div class="field span-2"><label for="observaciones">Observaciones</label><textarea id="observaciones" formControlName="observaciones"></textarea></div>@if(!codigo){<div class="field span-2"><label for="responsable">Responsable del registro *</label><input id="responsable" maxlength="150" formControlName="responsable" [class.invalid]="invalid('responsable')" />@if(invalid('responsable')){<p class="field-error">El responsable es obligatorio.</p>}</div>}</div>
<div class="form-actions"><a class="btn btn--secondary" [routerLink]="codigo?['/dispositivos',codigo]:['/dispositivos']">Cancelar</a><button class="btn btn--primary" type="submit" [disabled]="submitting()">{{submitting()?'Guardando…':'Guardar dispositivo'}}</button></div></form>}`,styles:[`.form-card{max-width:58rem;padding:1.4rem}`]})
export class DispositivoForm implements OnInit{
 private readonly fb=inject(FormBuilder);private readonly service=inject(DispositivosService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);
 protected codigo=0;protected readonly loading=signal(false);protected readonly submitting=signal(false);protected readonly apiError=signal('');
 protected readonly form=this.fb.nonNullable.group({codigoInventario:[0,[Validators.required,Validators.min(1),Validators.pattern(/^\d+$/)]],tipoDispositivo:['',[Validators.required,Validators.maxLength(80)]],marca:['',[Validators.maxLength(100)]],modelo:['',[Validators.maxLength(150)]],numeroSerie:['',[Validators.maxLength(150)]],imei:['',[Validators.maxLength(30)]],localidad:['',[Validators.maxLength(120)]],ubicacionDetalle:['',[Validators.maxLength(250)]],observaciones:[''],responsable:['',[Validators.required,Validators.maxLength(150)]]});
 ngOnInit(){this.codigo=Number(this.route.snapshot.paramMap.get('codigo')||0);if(this.codigo){this.form.controls.codigoInventario.clearValidators();this.form.controls.responsable.clearValidators();this.loading.set(true);this.service.obtener(this.codigo).subscribe({next:i=>{this.form.patchValue({tipoDispositivo:i.tipoDispositivo,marca:i.marca||'',modelo:i.modelo||'',numeroSerie:i.numeroSerie||'',imei:i.imei||'',localidad:i.localidad||'',ubicacionDetalle:i.ubicacionDetalle||'',observaciones:i.observaciones||''});this.loading.set(false)},error:e=>{this.apiError.set(errorMessage(e));this.loading.set(false)}})}}
 protected invalid(name:keyof typeof this.form.controls){const c=this.form.controls[name];return c.invalid&&(c.dirty||c.touched)}
 protected submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.submitting.set(true);this.apiError.set('');const v=this.form.getRawValue();const base={tipoDispositivo:v.tipoDispositivo.trim(),marca:v.marca.trim()||null,modelo:v.modelo.trim()||null,numeroSerie:v.numeroSerie.trim()||null,imei:v.imei.trim()||null,localidad:v.localidad.trim()||null,ubicacionDetalle:v.ubicacionDetalle.trim()||null,observaciones:v.observaciones.trim()||null};const request=this.codigo?this.service.actualizar(this.codigo,base):this.service.crear({...base,codigoInventario:v.codigoInventario,responsable:v.responsable.trim()});request.subscribe({next:i=>this.router.navigate(['/dispositivos',i.codigoInventario]),error:e=>{this.apiError.set(errorMessage(e));this.submitting.set(false)}})}
}
