import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { Colaborador, Departamento, Dispositivo, Estado, HistorialEvento } from '../../core/models/itam.models';
import { ColaboradoresService } from '../../core/services/colaboradores.service';
import { ConfirmationService } from '../../core/services/confirmation.service';
import { DepartamentosService } from '../../core/services/departamentos.service';
import { DispositivosService } from '../../core/services/dispositivos.service';
import { EstadosService } from '../../core/services/estados.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

type DeviceAction='assign-person'|'assign-department'|'return'|'state';

@Component({selector:'app-dispositivo-detail',imports:[DatePipe,ReactiveFormsModule,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Detalle del dispositivo" subtitle="Ficha técnica, custodia actual y trazabilidad completa.">@if(item();as d){<a class="btn btn--secondary" [routerLink]="['editar']">Editar ficha</a>}</app-page-header>
@if(notice()){<div class="notice notice--success">{{notice()}}</div>}@if(loading()){<section class="card"><app-view-state kind="loading" title="Cargando dispositivo" /></section>}@else if(error()){<section class="card"><app-view-state kind="error" title="No se pudo cargar" [message]="error()" (retry)="load()" /></section>}@else if(item();as d){
<section class="card device-head"><div><span class="asset-code">ACTIVO #{{d.codigoInventario}}</span><h2>{{d.tipoDispositivo}} · {{d.marca||'Sin marca'}} {{d.modelo||''}}</h2><p>{{d.numeroSerie?'Serie '+d.numeroSerie:'Sin número de serie'}}</p></div><app-status-badge [code]="d.estado.codigo" [label]="d.estado.nombre" /></section>
@if(terminal()){<div class="notice notice--error">El dispositivo está en un estado terminal. Cambia su estado explícitamente antes de realizar una asignación.</div>}
<div class="action-bar"><button class="btn btn--primary" type="button" [disabled]="terminal()" (click)="open('assign-person')">Asignar a colaborador</button><button class="btn btn--secondary" type="button" [disabled]="terminal()" (click)="open('assign-department')">Asignar a departamento</button>@if((d.colaborador||d.departamento)&&!terminal()){<button class="btn btn--danger" type="button" (click)="open('return')">Registrar devolución</button>}<button class="btn btn--secondary" type="button" (click)="open('state')">Cambiar estado</button></div>
<section class="detail-columns"><article class="card detail-card"><h3>Información técnica</h3><dl class="detail-grid"><div class="detail-item"><dt>Tipo</dt><dd>{{d.tipoDispositivo}}</dd></div><div class="detail-item"><dt>Marca</dt><dd>{{d.marca||'—'}}</dd></div><div class="detail-item"><dt>Modelo</dt><dd>{{d.modelo||'—'}}</dd></div><div class="detail-item"><dt>Serie</dt><dd>{{d.numeroSerie||'—'}}</dd></div><div class="detail-item"><dt>IMEI</dt><dd>{{d.imei||'—'}}</dd></div><div class="detail-item"><dt>Fecha registro</dt><dd>{{d.fechaRegistro|date:'dd-MM-yyyy'}}</dd></div><div class="detail-item"><dt>Localidad</dt><dd>{{d.localidad||'—'}}</dd></div><div class="detail-item"><dt>Ubicación</dt><dd>{{d.ubicacionDetalle||'—'}}</dd></div><div class="detail-item"><dt>SIM asociada</dt><dd>{{d.simAsociada?'#'+d.simAsociada.codigoInventario:'—'}}</dd></div><div class="detail-item span-all"><dt>Observaciones</dt><dd>{{d.observaciones||'—'}}</dd></div></dl></article>
<article class="card custody-card"><h3>Custodia actual</h3>@if(d.colaborador){<div class="custody"><span class="custody-icon">P</span><div><strong>{{d.colaborador.nombre}}</strong><p>{{d.colaborador.rut}} · {{d.colaborador.cargo||'Sin cargo'}}</p></div></div>}@else if(d.departamento){<div class="custody"><span class="custody-icon">D</span><div><strong>{{d.departamento.nombre}}</strong><p>Recibido por {{d.recibidoPor?.nombre||'—'}}</p></div></div>}@else{<div class="no-custody"><strong>Sin custodia</strong><p>El activo no está asignado actualmente.</p></div>}<dl><div><dt>Estado</dt><dd>{{d.estado.nombre}}</dd></div><div><dt>Actualizado</dt><dd>{{d.actualizadoEn|date:'dd-MM-yyyy HH:mm'}}</dd></div></dl></article></section>
<section class="card history-card"><h3>Historial del activo</h3>@if(!history().length){<p class="text-muted">Todavía no existen eventos registrados.</p>}@else{<div class="timeline">@for(event of history();track event.id){<div class="timeline-item"><strong>{{event.tipoEvento.replaceAll('_',' ')}}</strong><p>{{event.estadoAnterior?.nombre||'Sin estado'}} → {{event.estadoNuevo?.nombre||'Sin cambio'}} · {{event.responsable}}</p>@if(event.observaciones){<p>{{event.observaciones}}</p>}<time>{{event.fechaEvento|date:'dd-MM-yyyy HH:mm'}}</time></div>}</div>}</section>
}
@if(action()){<div class="dialog-backdrop" (click)="closeBackdrop($event)"><form class="dialog" [formGroup]="actionForm" (ngSubmit)="execute()"><div class="dialog-header"><div><h2>{{actionTitle()}}</h2><p>La API validará las reglas definitivas de inventario.</p></div><button type="button" class="icon-button" (click)="action.set(null)">×</button></div>@if(actionError()){<div class="notice notice--error">{{actionError()}}</div>}<div class="form-grid">
@if(action()==='assign-person'){<div class="field span-2"><label for="colaborador">Colaborador *</label><select id="colaborador" formControlName="colaboradorId"><option value="">Seleccionar</option>@for(c of collaborators();track c.id){<option [value]="c.id">{{c.nombre}} · {{c.rut}}</option>}</select></div>}
@if(action()==='assign-department'){<div class="field"><label for="dept">Departamento *</label><select id="dept" formControlName="departamentoId"><option value="">Seleccionar</option>@for(dep of departments();track dep.id){<option [value]="dep.id">{{dep.nombre}}</option>}</select></div><div class="field"><label for="receiver">Recibido por *</label><select id="receiver" formControlName="recibidoPorId"><option value="">Seleccionar</option>@for(c of collaborators();track c.id){<option [value]="c.id">{{c.nombre}}</option>}</select></div><div class="field"><label for="location">Localidad</label><input id="location" formControlName="localidad" maxlength="120" /></div><div class="field"><label for="position">Ubicación</label><input id="position" formControlName="ubicacionDetalle" maxlength="250" /></div>}
@if(action()==='state'){<div class="field span-2"><label for="new-state">Nuevo estado *</label><select id="new-state" formControlName="estadoId"><option value="">Seleccionar</option>@for(e of states();track e.id){<option [value]="e.id">{{e.nombre}}{{e.esTerminal?' · terminal':''}}</option>}</select></div>}
<div class="field span-2"><label for="responsible">Responsable *</label><input id="responsible" formControlName="responsable" maxlength="150" /></div><div class="field span-2"><label for="action-notes">Observaciones</label><textarea id="action-notes" formControlName="observaciones"></textarea></div></div><div class="form-actions"><button class="btn btn--secondary" type="button" (click)="action.set(null)">Cancelar</button><button class="btn btn--primary" type="submit" [disabled]="submitting()">{{submitting()?'Procesando…':'Confirmar operación'}}</button></div></form></div>}
`,styleUrl:'./dispositivo-detail.scss'})
export class DispositivoDetail implements OnInit{
 private readonly service=inject(DispositivosService);private readonly estadosService=inject(EstadosService);private readonly colaboradoresService=inject(ColaboradoresService);private readonly departamentosService=inject(DepartamentosService);private readonly confirmation=inject(ConfirmationService);private readonly route=inject(ActivatedRoute);private readonly fb=inject(FormBuilder);
 protected readonly item=signal<Dispositivo|null>(null);protected readonly history=signal<HistorialEvento[]>([]);protected readonly states=signal<Estado[]>([]);protected readonly collaborators=signal<Colaborador[]>([]);protected readonly departments=signal<Departamento[]>([]);protected readonly loading=signal(true);protected readonly error=signal('');protected readonly notice=signal('');protected readonly actionError=signal('');protected readonly submitting=signal(false);protected readonly action=signal<DeviceAction|null>(null);private codigo=0;
 protected readonly actionForm=this.fb.nonNullable.group({colaboradorId:[''],departamentoId:[''],recibidoPorId:[''],localidad:[''],ubicacionDetalle:[''],estadoId:[''],responsable:['',[Validators.required,Validators.maxLength(150)]],observaciones:['']});
 ngOnInit(){this.codigo=Number(this.route.snapshot.paramMap.get('codigo'));this.load()}
  protected load(){this.loading.set(true);this.error.set('');forkJoin({item:this.service.obtener(this.codigo),history:this.service.historial(this.codigo),states:this.estadosService.listar('DISPOSITIVO'),collaborators:this.colaboradoresService.listar({activo:true}),departments:this.departamentosService.listar()}).subscribe({next:r=>{this.item.set(r.item);this.history.set(r.history);this.states.set(r.states.filter(e=>e.activo));this.collaborators.set(r.collaborators);this.departments.set(r.departments.filter(d=>d.activo));this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}
 protected terminal(){return this.states().find(e=>e.id===this.item()?.estado.id)?.esTerminal??false}
 protected open(action:DeviceAction){this.actionForm.reset({colaboradorId:'',departamentoId:'',recibidoPorId:'',localidad:this.item()?.localidad||'',ubicacionDetalle:this.item()?.ubicacionDetalle||'',estadoId:'',responsable:'',observaciones:''});this.actionError.set('');this.action.set(action)}
 protected actionTitle(){return{'assign-person':'Asignar a colaborador','assign-department':'Asignar a departamento','return':'Registrar devolución','state':'Cambiar estado'}[this.action()||'return']}
 protected closeBackdrop(event:MouseEvent){if(event.target===event.currentTarget)this.action.set(null)}
 protected execute(){const a=this.action();if(!a)return;const v=this.actionForm.getRawValue();if(!v.responsable.trim()){this.actionForm.controls.responsable.markAsTouched();return}if(a==='assign-person'&&!v.colaboradorId){this.actionError.set('Selecciona un colaborador.');return}if(a==='assign-department'&&(!v.departamentoId||!v.recibidoPorId)){this.actionError.set('Selecciona departamento y receptor.');return}if(a==='state'&&!v.estadoId){this.actionError.set('Selecciona un estado.');return}if(a==='return'&&!this.confirmation.confirm('¿Confirmas la devolución? Se limpiará la custodia y el equipo quedará retenido para revisión.'))return;const target=this.states().find(e=>e.id===v.estadoId);if(a==='state'&&target?.esTerminal&&!this.confirmation.confirm(`¿Confirmas el cambio al estado terminal ${target.nombre}?`))return;
 const common={responsable:v.responsable.trim(),observaciones:v.observaciones.trim()||null};let request:Observable<Dispositivo>;
 if(a==='assign-person')request=this.service.asignarColaborador(this.codigo,{...common,colaboradorId:Number(v.colaboradorId)});else if(a==='assign-department')request=this.service.asignarDepartamento(this.codigo,{...common,departamentoId:Number(v.departamentoId),recibidoPorId:Number(v.recibidoPorId),localidad:v.localidad.trim()||null,ubicacionDetalle:v.ubicacionDetalle.trim()||null});else if(a==='return')request=this.service.devolver(this.codigo,common);else request=this.service.cambiarEstado(this.codigo,{...common,estadoId:Number(v.estadoId)});
 this.submitting.set(true);this.actionError.set('');request.subscribe({next:()=>{this.action.set(null);this.submitting.set(false);this.notice.set('Operación registrada correctamente.');this.load()},error:e=>{this.actionError.set(errorMessage(e));this.submitting.set(false)}})}
}
