import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Estado, Sim } from '../../core/models/itam.models';
import { EstadosService } from '../../core/services/estados.service';
import { SimService } from '../../core/services/sim.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-sim-list',imports:[FormsModule,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Tarjetas SIM" subtitle="Líneas corporativas, asignaciones y asociación con dispositivos."><a class="btn btn--primary" routerLink="nuevo">+ Nueva SIM</a></app-page-header>
<section class="card"><div class="toolbar"><div class="field"><label for="q">Buscar</label><input id="q" [(ngModel)]="query" placeholder="Código, ICCID, número o compañía" /></div><div class="field"><label for="state">Estado</label><select id="state" [(ngModel)]="state"><option value="">Todos</option>@for(e of states();track e.id){<option [value]="e.codigo">{{e.nombre}}</option>}</select></div></div>
@if(loading()){<app-view-state kind="loading" title="Cargando tarjetas SIM" />}@else if(error()){<app-view-state kind="error" title="No se pudo cargar" [message]="error()" (retry)="load()" />}@else if(!filtered().length){<app-view-state kind="empty" title="Sin resultados" message="No hay SIM que coincidan con los filtros." />}@else{<div class="table-wrap"><table class="data-table"><thead><tr><th>Inventario</th><th>Identificación</th><th>Compañía</th><th>Estado</th><th>Asignación</th><th>Dispositivo</th><th></th></tr></thead><tbody>@for(item of filtered();track item.id){<tr><td><a class="asset-link" [routerLink]="[item.codigoInventario]">#{{item.codigoInventario}}</a></td><td><span class="cell-primary">{{item.numeroAsociado||'Sin número'}}</span><span class="cell-secondary">ICCID {{item.iccidCodigoFabrica}}</span></td><td>{{item.compania||'—'}}</td><td><app-status-badge [code]="item.estado.codigo" [label]="item.estado.nombre" /></td><td>{{item.colaborador?.nombre||'Sin asignar'}}</td><td>{{item.dispositivo?'#'+item.dispositivo.codigoInventario:'Sin asociar'}}</td><td><div class="actions"><a class="btn btn--ghost btn--small" [routerLink]="[item.codigoInventario]">Ver</a><a class="btn btn--ghost btn--small" [routerLink]="[item.codigoInventario,'editar']">Editar</a></div></td></tr>}</tbody></table></div>}</section>`,styles:[`.asset-link{color:var(--color-primary);font-weight:800;text-decoration:none}`]})
export class SimList implements OnInit{private readonly service=inject(SimService);private readonly estados=inject(EstadosService);protected readonly items=signal<Sim[]>([]);protected readonly states=signal<Estado[]>([]);protected readonly loading=signal(true);protected readonly error=signal('');protected query='';protected state='';ngOnInit(){this.estados.listar('SIM').subscribe({next:i=>this.states.set(i)});this.load()}protected load(){this.loading.set(true);this.service.listar().subscribe({next:i=>{this.items.set(i);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}protected filtered(){const q=this.query.trim().toLowerCase();return this.items().filter(i=>(!this.state||i.estado.codigo===this.state)&&(!q||String(i.codigoInventario).includes(q)||i.iccidCodigoFabrica.toLowerCase().includes(q)||(i.numeroAsociado||'').toLowerCase().includes(q)||(i.compania||'').toLowerCase().includes(q)))}}
