import { DatePipe } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { Colaborador, Dispositivo, Estado, HistorialEvento, Sim } from '../../core/models/itam.models';
import { ColaboradoresService } from '../../core/services/colaboradores.service';
import { ConfirmationService } from '../../core/services/confirmation.service';
import { DispositivosService } from '../../core/services/dispositivos.service';
import { EstadosService } from '../../core/services/estados.service';
import { SimService } from '../../core/services/sim.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { StatusBadge } from '../../shared/components/status-badge/status-badge';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

type SimAction='associate'|'dissociate'|'assign'|'unassign'|'state';

@Component({selector:'app-sim-detail',imports:[DatePipe,ReactiveFormsModule,RouterLink,PageHeader,StatusBadge,ViewState],template:`
<app-page-header title="Detalle de SIM" subtitle="Asignación de línea, dispositivo asociado y trazabilidad.">@if(item()){<a class="btn btn--secondary" [routerLink]="['editar']">Editar ficha</a>}</app-page-header>
@if(notice()){<div class="notice notice--success">{{notice()}}</div>}@if(loading()){<section class="card"><app-view-state kind="loading" title="Cargando SIM" /></section>}@else if(error()){<section class="card"><app-view-state kind="error" title="No se pudo cargar" [message]="error()" (retry)="load()" /></section>}@else if(item();as s){
<section class="card sim-head"><div><span class="asset-code">SIM #{{s.codigoInventario}}</span><h2>{{s.numeroAsociado||'Línea sin número asociado'}}</h2><p>ICCID {{s.iccidCodigoFabrica}}</p></div><app-status-badge [code]="s.estado.codigo" [label]="s.estado.nombre" /></section>
@if(!operable()){<div class="notice notice--error">Esta SIM está en un estado no operable. Debes cambiar su estado explícitamente antes de asociar o asignar.</div>}
<div class="action-bar">@if(!s.dispositivo){<button class="btn btn--primary" type="button" [disabled]="!operable()" (click)="open('associate')">Asociar dispositivo</button>}@else{<button class="btn btn--danger" type="button" [disabled]="!operable()" (click)="open('dissociate')">Desasociar dispositivo</button>}@if(!s.colaborador){<button class="btn btn--primary" type="button" [disabled]="!operable()" (click)="open('assign')">Asignar colaborador</button>}@else{<button class="btn btn--danger" type="button" [disabled]="!operable()" (click)="open('unassign')">Desasignar colaborador</button>}<button class="btn btn--secondary" type="button" (click)="open('state')">Cambiar estado</button></div>
<section class="detail-columns"><article class="card detail-card"><h3>Información de la línea</h3><dl class="detail-grid"><div class="detail-item"><dt>Código inventario</dt><dd>#{{s.codigoInventario}}</dd></div><div class="detail-item"><dt>ICCID</dt><dd>{{s.iccidCodigoFabrica}}</dd></div><div class="detail-item"><dt>Número</dt><dd>{{s.numeroAsociado||'—'}}</dd></div><div class="detail-item"><dt>Compañía</dt><dd>{{s.compania||'—'}}</dd></div><div class="detail-item"><dt>Fecha registro</dt><dd>{{s.fechaRegistro|date:'dd-MM-yyyy'}}</dd></div><div class="detail-item"><dt>Actualizada</dt><dd>{{s.actualizadoEn|date:'dd-MM-yyyy HH:mm'}}</dd></div><div class="detail-item span-all"><dt>Observaciones</dt><dd>{{s.observaciones||'—'}}</dd></div></dl></article><article class="card links-card"><h3>Vínculos actuales</h3><div class="link-block"><span>Colaborador</span><strong>{{s.colaborador?.nombre||'Sin asignar'}}</strong><small>{{s.colaborador?.rut||'No existe una custodia personal'}}</small></div><div class="link-block"><span>Dispositivo</span><strong>{{s.dispositivo?'Activo #'+s.dispositivo.codigoInventario:'Sin asociar'}}</strong><small>{{s.dispositivo?.tipoDispositivo||'No existe un equipo vinculado'}}</small></div></article></section>
<section class="card history-card"><h3>Historial de la SIM</h3>@if(!history().length){<p class="text-muted">Todavía no existen eventos registrados.</p>}@else{<div class="timeline">@for(event of history();track event.id){<div class="timeline-item"><strong>{{event.tipoEvento.replaceAll('_',' ')}}</strong><p>{{event.estadoAnterior?.nombre||'Sin estado'}} → {{event.estadoNuevo?.nombre||'Sin cambio'}} · {{event.responsable}}</p>@if(event.observaciones){<p>{{event.observaciones}}</p>}<time>{{event.fechaEvento|date:'dd-MM-yyyy HH:mm'}}</time></div>}</div>}</section>}
@if(action()){<div class="dialog-backdrop" (click)="closeBackdrop($event)"><form class="dialog" [formGroup]="actionForm" (ngSubmit)="execute()"><div class="dialog-header"><div><h2>{{actionTitle()}}</h2><p>La operación quedará registrada en el historial.</p></div><button class="icon-button" type="button" (click)="action.set(null)">×</button></div>@if(actionError()){<div class="notice notice--error">{{actionError()}}</div>}<div class="form-grid">
@if(action()==='associate'){<div class="field span-2"><label for="device">Dispositivo sin SIM *</label><select id="device" formControlName="dispositivoCodigo"><option value="">Seleccionar</option>@for(d of availableDevices();track d.id){<option [value]="d.codigoInventario">#{{d.codigoInventario}} · {{d.tipoDispositivo}} {{d.marca||''}} {{d.modelo||''}}</option>}</select></div>}
@if(action()==='assign'){<div class="field span-2"><label for="person">Colaborador *</label><select id="person" formControlName="colaboradorId"><option value="">Seleccionar</option>@for(c of collaborators();track c.id){<option [value]="c.id">{{c.nombre}} · {{c.rut}}</option>}</select></div>}
@if(action()==='state'){<div class="field span-2"><label for="new-state">Nuevo estado *</label><select id="new-state" formControlName="estadoId"><option value="">Seleccionar</option>@for(e of states();track e.id){<option [value]="e.id">{{e.nombre}}{{e.esTerminal?' · terminal':''}}</option>}</select></div>}
<div class="field span-2"><label for="responsible">Responsable *</label><input id="responsible" maxlength="150" formControlName="responsable" /></div><div class="field span-2"><label for="notes">Observaciones</label><textarea id="notes" formControlName="observaciones"></textarea></div></div><div class="form-actions"><button class="btn btn--secondary" type="button" (click)="action.set(null)">Cancelar</button><button class="btn btn--primary" [disabled]="submitting()" type="submit">{{submitting()?'Procesando…':'Confirmar operación'}}</button></div></form></div>}
`,styleUrl:'./sim-detail.scss'})
export class SimDetail implements OnInit{
 private readonly service=inject(SimService);private readonly estadosService=inject(EstadosService);private readonly dispositivosService=inject(DispositivosService);private readonly colaboradoresService=inject(ColaboradoresService);private readonly confirmation=inject(ConfirmationService);private readonly route=inject(ActivatedRoute);private readonly fb=inject(FormBuilder);
 protected readonly item=signal<Sim|null>(null);protected readonly history=signal<HistorialEvento[]>([]);protected readonly states=signal<Estado[]>([]);protected readonly devices=signal<Dispositivo[]>([]);protected readonly collaborators=signal<Colaborador[]>([]);protected readonly loading=signal(true);protected readonly error=signal('');protected readonly notice=signal('');protected readonly actionError=signal('');protected readonly submitting=signal(false);protected readonly action=signal<SimAction|null>(null);private codigo=0;
 protected readonly actionForm=this.fb.nonNullable.group({dispositivoCodigo:[''],colaboradorId:[''],estadoId:[''],responsable:['',[Validators.required,Validators.maxLength(150)]],observaciones:['']});
 ngOnInit(){this.codigo=Number(this.route.snapshot.paramMap.get('codigo'));this.load()}
 protected load(){this.loading.set(true);this.error.set('');forkJoin({item:this.service.obtener(this.codigo),history:this.service.historial(this.codigo),states:this.estadosService.listar('SIM'),devices:this.dispositivosService.listar(),collaborators:this.colaboradoresService.listar({activo:true})}).subscribe({next:r=>{this.item.set(r.item);this.history.set(r.history);this.states.set(r.states.filter(e=>e.activo));this.devices.set(r.devices);this.collaborators.set(r.collaborators);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}
 protected operable(){return['DISPONIBLE','ASIGNADA'].includes(this.item()?.estado.codigo||'')}protected availableDevices(){return this.devices().filter(d=>!d.simAsociada)}
 protected open(action:SimAction){this.actionForm.reset({dispositivoCodigo:'',colaboradorId:'',estadoId:'',responsable:'',observaciones:''});this.actionError.set('');this.action.set(action)}
 protected actionTitle(){return{associate:'Asociar dispositivo',dissociate:'Desasociar dispositivo',assign:'Asignar colaborador',unassign:'Desasignar colaborador',state:'Cambiar estado'}[this.action()||'state']}
 protected closeBackdrop(event:MouseEvent){if(event.target===event.currentTarget)this.action.set(null)}
 protected execute(){const a=this.action();if(!a)return;const v=this.actionForm.getRawValue();if(!v.responsable.trim()){this.actionError.set('El responsable es obligatorio.');return}if(a==='associate'&&!v.dispositivoCodigo){this.actionError.set('Selecciona un dispositivo.');return}if(a==='assign'&&!v.colaboradorId){this.actionError.set('Selecciona un colaborador.');return}if(a==='state'&&!v.estadoId){this.actionError.set('Selecciona un estado.');return}if(a==='dissociate'&&!this.confirmation.confirm('¿Confirmas la desasociación de esta SIM y su dispositivo?'))return;if(a==='unassign'&&!this.confirmation.confirm('¿Confirmas la desasignación de esta SIM y su colaborador?'))return;const target=this.states().find(e=>e.id===v.estadoId);if(a==='state'&&target?.esTerminal&&!this.confirmation.confirm(`¿Confirmas el cambio al estado terminal ${target.nombre}?`))return;
 const common={responsable:v.responsable.trim(),observaciones:v.observaciones.trim()||null};let request:Observable<Sim>;if(a==='associate')request=this.service.asociarDispositivo(this.codigo,{...common,dispositivoCodigoInventario:Number(v.dispositivoCodigo)});else if(a==='dissociate')request=this.service.desasociarDispositivo(this.codigo,common);else if(a==='assign')request=this.service.asignarColaborador(this.codigo,{...common,colaboradorId:Number(v.colaboradorId)});else if(a==='unassign')request=this.service.desasignarColaborador(this.codigo,common);else request=this.service.cambiarEstado(this.codigo,{...common,estadoId:Number(v.estadoId)});this.submitting.set(true);request.subscribe({next:()=>{this.action.set(null);this.submitting.set(false);this.notice.set('Operación registrada correctamente.');this.load()},error:e=>{this.actionError.set(errorMessage(e));this.submitting.set(false)}})}
}
