import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { SimService } from '../../core/services/sim.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

@Component({selector:'app-sim-form',imports:[ReactiveFormsModule,RouterLink,PageHeader,ViewState],template:`
<app-page-header [title]="codigo?'Editar SIM':'Nueva SIM'" subtitle="Registro de identificación y datos comerciales de la línea." />
@if(loading()){<section class="card"><app-view-state kind="loading" title="Cargando SIM" /></section>}@else{<form class="card form-card" [formGroup]="form" (ngSubmit)="submit()">@if(apiError()){<div class="notice notice--error">{{apiError()}}</div>}<div class="form-grid">@if(!codigo){<div class="field"><label for="code">Código de inventario *</label><input id="code" type="number" min="1" formControlName="codigoInventario" [class.invalid]="invalid('codigoInventario')" />@if(invalid('codigoInventario')){<p class="field-error">Debe ser un entero positivo.</p>}</div>}@else{<div class="field"><label>Código de inventario</label><input [value]="codigo" disabled /></div>}<div class="field"><label for="iccid">ICCID / código de fábrica *</label><input id="iccid" maxlength="32" formControlName="iccidCodigoFabrica" [class.invalid]="invalid('iccidCodigoFabrica')" />@if(invalid('iccidCodigoFabrica')){<p class="field-error">El ICCID es obligatorio (máximo 32 caracteres).</p>}</div><div class="field"><label for="number">Número asociado</label><input id="number" maxlength="30" formControlName="numeroAsociado" /></div><div class="field"><label for="company">Compañía</label><input id="company" maxlength="100" formControlName="compania" /></div><div class="field span-2"><label for="notes">Observaciones</label><textarea id="notes" formControlName="observaciones"></textarea></div>@if(!codigo){<div class="field span-2"><label for="responsible">Responsable del registro *</label><input id="responsible" maxlength="150" formControlName="responsable" [class.invalid]="invalid('responsable')" />@if(invalid('responsable')){<p class="field-error">El responsable es obligatorio.</p>}</div>}</div><div class="form-actions"><a class="btn btn--secondary" [routerLink]="codigo?['/sim',codigo]:['/sim']">Cancelar</a><button class="btn btn--primary" type="submit" [disabled]="submitting()">{{submitting()?'Guardando…':'Guardar SIM'}}</button></div></form>}`,styles:[`.form-card{max-width:52rem;padding:1.4rem}`]})
export class SimForm implements OnInit{private readonly fb=inject(FormBuilder);private readonly service=inject(SimService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);protected codigo=0;protected readonly loading=signal(false);protected readonly submitting=signal(false);protected readonly apiError=signal('');protected readonly form=this.fb.nonNullable.group({codigoInventario:[0,[Validators.required,Validators.min(1),Validators.pattern(/^\d+$/)]],iccidCodigoFabrica:['',[Validators.required,Validators.maxLength(32)]],numeroAsociado:['',[Validators.maxLength(30)]],compania:['',[Validators.maxLength(100)]],observaciones:[''],responsable:['',[Validators.required,Validators.maxLength(150)]]});ngOnInit(){this.codigo=Number(this.route.snapshot.paramMap.get('codigo')||0);if(this.codigo){this.form.controls.codigoInventario.clearValidators();this.form.controls.responsable.clearValidators();this.loading.set(true);this.service.obtener(this.codigo).subscribe({next:i=>{this.form.patchValue({iccidCodigoFabrica:i.iccidCodigoFabrica,numeroAsociado:i.numeroAsociado||'',compania:i.compania||'',observaciones:i.observaciones||''});this.loading.set(false)},error:e=>{this.apiError.set(errorMessage(e));this.loading.set(false)}})}}protected invalid(name:keyof typeof this.form.controls){const c=this.form.controls[name];return c.invalid&&(c.dirty||c.touched)}protected submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.submitting.set(true);const v=this.form.getRawValue();const base={iccidCodigoFabrica:v.iccidCodigoFabrica.trim(),numeroAsociado:v.numeroAsociado.trim()||null,compania:v.compania.trim()||null,observaciones:v.observaciones.trim()||null};const request=this.codigo?this.service.actualizar(this.codigo,base):this.service.crear({...base,codigoInventario:v.codigoInventario,responsable:v.responsable.trim()});request.subscribe({next:i=>this.router.navigate(['/sim',i.codigoInventario]),error:e=>{this.apiError.set(errorMessage(e));this.submitting.set(false)}})}}
