import { Component, OnInit, inject, signal } from '@angular/core';
import { forkJoin } from 'rxjs';
import { LucideBuilding, LucideCardSim, LucideCircleAlert, LucideCircleCheck, LucideDynamicIcon, LucidePackage, LucidePackageOpen, LucideUsers, type LucideIconInput } from '@lucide/angular';
import { ColaboradoresService } from '../../core/services/colaboradores.service';
import { DepartamentosService } from '../../core/services/departamentos.service';
import { DispositivosService } from '../../core/services/dispositivos.service';
import { HealthService } from '../../core/services/health.service';
import { SimService } from '../../core/services/sim.service';
import { PageHeader } from '../../shared/components/page-header/page-header';
import { ViewState } from '../../shared/components/view-state/view-state';
import { errorMessage } from '../../shared/utils/error-message';

interface Metric { label:string; value:number; meta:string; tone:string; icon:LucideIconInput; }
interface TypeSummary { label:string; count:number; percentage:number; }

@Component({selector:'app-dashboard',imports:[PageHeader,ViewState,LucideDynamicIcon,LucideCircleCheck,LucideCircleAlert],template:`
<app-page-header title="Dashboard Gerencial" subtitle="Resumen del inventario tecnológico de Aguas San Isidro." eyebrow="Control patrimonial y operativo" />
@if(loading()){<section class="card"><app-view-state kind="loading" title="Consultando inventario" message="Consolidando indicadores desde la API…" /></section>}@else if(error()){<section class="card"><app-view-state kind="error" title="No pudimos cargar el dashboard" [message]="error()" (retry)="load()" /></section>}@else{
<section class="metric-grid" aria-label="Indicadores principales">@for(metric of metrics();track metric.label){<article class="card metric" [class]="'card metric metric--'+metric.tone"><div class="metric__head"><span class="metric__label">{{metric.label}}</span><span class="metric__icon"><svg [lucideIcon]="metric.icon"></svg></span></div><strong class="metric__value">{{metric.value}}</strong><p class="metric__meta">{{metric.meta}}</p></article>}</section>
<section class="dashboard-grid"><article class="card type-card"><div class="card-heading"><div><span>Distribución real</span><h2>Inventario por Tipo</h2></div><strong>{{totalDevices()}} activos</strong></div>@if(!typeSummary().length){<app-view-state kind="empty" title="Sin dispositivos" message="Registra activos para ver la distribución por tipo." />}@else{<div class="type-bars">@for(type of typeSummary();track type.label){<div class="type-row"><div><strong>{{type.label}}</strong><span>{{type.count}} {{type.count===1?'activo':'activos'}}</span></div><div class="bar" role="progressbar" [attr.aria-valuenow]="type.percentage" aria-valuemin="0" aria-valuemax="100"><span [style.width.%]="type.percentage"></span></div><b>{{type.percentage}}%</b></div>}</div>}</article>
<article class="card operational-card"><div class="card-heading"><div><span>Panorama operativo</span><h2>Recursos relacionados</h2></div></div><div class="mini-stat"><span class="mini-icon"><svg [lucideIcon]="simIcon"></svg></span><div><strong>{{totalSims()}}</strong><span>Tarjetas SIM</span></div></div><div class="mini-stat"><span class="mini-icon"><svg [lucideIcon]="usersIcon"></svg></span><div><strong>{{activePeople()}}</strong><span>Colaboradores activos</span></div></div><div class="mini-stat"><span class="mini-icon"><svg [lucideIcon]="buildingIcon"></svg></span><div><strong>{{activeDepartments()}}</strong><span>Departamentos activos</span></div></div></article></section>
<section class="card integration"><div><span class="integration__icon"><svg lucideCircleCheck></svg></span><div><strong>Plataforma conectada</strong><p>API ITAM y PostgreSQL responden correctamente.</p></div></div><div class="service-pills"><span>API {{apiStatus()}}</span><span>PostgreSQL {{databaseStatus()}}</span></div></section>
<p class="scope-note"><svg lucideCircleAlert></svg><span>Los últimos movimientos globales requieren un endpoint agregado para evitar consultar el historial de cada activo individualmente.</span></p>}
`,styleUrl:'./dashboard.scss'})
export class Dashboard implements OnInit{
 private readonly dispositivos=inject(DispositivosService);private readonly sims=inject(SimService);private readonly colaboradores=inject(ColaboradoresService);private readonly departamentos=inject(DepartamentosService);private readonly health=inject(HealthService);
 protected readonly loading=signal(true);protected readonly error=signal('');protected readonly metrics=signal<Metric[]>([]);protected readonly typeSummary=signal<TypeSummary[]>([]);protected readonly totalDevices=signal(0);protected readonly totalSims=signal(0);protected readonly activePeople=signal(0);protected readonly activeDepartments=signal(0);protected readonly apiStatus=signal('—');protected readonly databaseStatus=signal('—');
 protected readonly simIcon=LucideCardSim;protected readonly usersIcon=LucideUsers;protected readonly buildingIcon=LucideBuilding;
 ngOnInit(){this.load()}
 protected load(){this.loading.set(true);this.error.set('');forkJoin({devices:this.dispositivos.listar(),sims:this.sims.listar(),people:this.colaboradores.listar(),departments:this.departamentos.listar(),health:this.health.health(),database:this.health.database()}).subscribe({next:r=>{const available=r.devices.filter(i=>i.estado.codigo==='DISPONIBLE').length;const assigned=r.devices.filter(i=>i.estado.codigo==='ASIGNADO').length;const lost=r.devices.filter(i=>i.estado.codigo.includes('EXTRAVIAD')).length;const retired=r.devices.filter(i=>i.estado.codigo.includes('BAJA')).length;this.metrics.set([{label:'Inventario físico',value:r.devices.length,meta:'Activos registrados',tone:'blue',icon:LucidePackage},{label:'En Bodega',value:available,meta:'Disponibles',tone:'cyan',icon:LucidePackageOpen},{label:'Asignados',value:assigned,meta:'Con custodia vigente',tone:'green',icon:LucideUsers},{label:'Extraviados',value:lost,meta:'Requieren seguimiento',tone:'dark',icon:LucideCircleAlert},{label:'Bajas',value:retired,meta:'Retirados del servicio',tone:'red',icon:LucideCircleAlert}]);const counts=new Map<string,number>();for(const item of r.devices)counts.set(item.tipo.nombre,(counts.get(item.tipo.nombre)??0)+1);this.typeSummary.set([...counts.entries()].sort((a,b)=>b[1]-a[1]).map(([label,count])=>({label,count,percentage:r.devices.length?Math.round(count*100/r.devices.length):0})));this.totalDevices.set(r.devices.length);this.totalSims.set(r.sims.length);this.activePeople.set(r.people.filter(i=>i.activo).length);this.activeDepartments.set(r.departments.filter(i=>i.activo).length);this.apiStatus.set(r.health.status);this.databaseStatus.set(r.database.status);this.loading.set(false)},error:e=>{this.error.set(errorMessage(e));this.loading.set(false)}})}
}
