import {DatePipe} from '@angular/common';
import {Component,input,output} from '@angular/core';
import {LucidePrinter,LucideX} from '@lucide/angular';
import {ComprobanteDevolucion} from '../../../core/models/itam.models';

@Component({selector:'app-comprobante-devolucion-preview',imports:[DatePipe,LucidePrinter,LucideX],template:`
<div class="dialog-backdrop" role="presentation" (click)="backdrop($event)"><section class="dialog return-document" role="dialog" aria-modal="true" aria-labelledby="return-title">
 <header><div><small>AGUAS SAN ISIDRO · DEPARTAMENTO DE TI</small><h2 id="return-title">Comprobante de devolución</h2><strong>{{comprobante().numeroComprobante}}</strong></div><button class="icon-button" type="button" aria-label="Cerrar" (click)="close.emit()"><svg lucideX></svg></button></header>
 <dl><div><dt>Fecha y hora</dt><dd>{{comprobante().fecha|date:'dd/MM/yyyy HH:mm'}}</dd></div><div><dt>Acta de origen</dt><dd>{{comprobante().actaEntrega?.numeroActa||'Sin acta asociada'}}</dd></div><div><dt>Persona que devuelve</dt><dd>{{comprobante().colaborador?.nombre||comprobante().devueltoPor?.nombre||'—'}}</dd></div><div><dt>RUT</dt><dd>{{comprobante().colaborador?.rut||comprobante().devueltoPor?.rut||'—'}}</dd></div><div><dt>Activo</dt><dd>{{comprobante().dispositivo.tipo}} · {{comprobante().dispositivo.marca||'—'}} {{comprobante().dispositivo.modelo||''}}</dd></div><div><dt>Código ITAM</dt><dd class="code">{{comprobante().dispositivo.codigoInventario}}</dd></div><div><dt>Resultado / condición</dt><dd>{{comprobante().resultado}} · {{comprobante().condicion||'Sin condición informada'}}</dd></div><div><dt>Responsable TI</dt><dd>{{comprobante().responsableTi}}</dd></div></dl>
 @if(comprobante().observaciones){<p class="return-notes"><strong>Observaciones</strong>{{comprobante().observaciones}}</p>}
 <footer><button class="btn btn--secondary" type="button" (click)="close.emit()">Cerrar</button><a class="btn btn--primary" [href]="pdfUrl()" target="_blank" rel="noopener"><svg lucidePrinter></svg>Ver / imprimir PDF</a></footer>
</section></div>`,styles:[`.return-document{max-width:48rem;padding:0}.return-document>header{align-items:flex-start;background:var(--navy);color:#fff;display:flex;justify-content:space-between;padding:1.3rem 1.5rem}.return-document header small{color:var(--cyan);font-weight:800;letter-spacing:.08em}.return-document h2{margin:.3rem 0}.return-document header strong{font-family:monospace}.return-document dl{display:grid;grid-template-columns:1fr 1fr;margin:0;padding:1.4rem}.return-document dl div{border-bottom:1px solid var(--gray-200);padding:.65rem}.return-document dt{color:var(--slate-500);font-size:.7rem}.return-document dd{font-weight:700;margin:.2rem 0}.return-notes{background:var(--gray-50);margin:0 1.4rem;padding:1rem}.return-notes strong{display:block;margin-bottom:.3rem}.return-document>footer{display:flex;gap:.7rem;justify-content:flex-end;padding:1.4rem}.return-document footer svg{height:1rem;width:1rem}@media(max-width:600px){.return-document dl{grid-template-columns:1fr}.return-document>footer{align-items:stretch;flex-direction:column}}` ]})
export class ComprobanteDevolucionPreview{readonly comprobante=input.required<ComprobanteDevolucion>();readonly pdfUrl=input.required<string>();readonly close=output<void>();protected backdrop(event:MouseEvent){if(event.target===event.currentTarget)this.close.emit();}}
